=encoding utf8


=head1 NAME

Mojolicious::Command::swat - Swat command


=head1 SYNOPSIS

    Usage: APPLICATION swat [OPTIONS]
    
    Options:
      -f, --force   Override existed swat tests


=head1 DESCRIPTION

L<Mojolicious::Command::swat|https://metacpan.org/pod/Mojolicious::Command::swat> 

=over

=item *

Generates L<swat|https://github.com/melezhik/swat> swat tests scaffolding for mojo application.



=item *

This command walks through all available routes and generates a swat test for every one. 



=back


=head1 INSTALL

    cpanm Mojolicious::Command::swat


=head1 EXAMPLE


=head2 install mojo

    sudo cpanm Mojolicious


=head2 bootstrap a mojo application

    mkdir myapp
    cd myapp
    mojo generate lite_app myapp.pl


=head2 define http resources ( mojo routes )

    $ nano myapp.pl
    
    #!/usr/bin/env perl
    use Mojolicious::Lite;
    
    get '/' => sub {
      my $c = shift;
      $c->render(text => 'ROOT');
    };
    
    
    post '/hello' => sub {
      my $c = shift;
      $c->render(text => 'HELLO');
    };
    
    get '/hello/world' => sub {
      my $c = shift;
      $c->render(text => 'HELLO WORLD');
    };
    
    app->start;
    
    
    $ ./myapp.pl routes
    /             GET
    /hello        POST  hello
    /hello/world  GET   helloworld


=head2 bootstrap swat tests

    $ ./myapp.pl swat
    generate swat route for / ...
    generate swat data for GET / ...
    generate swat route for /hello ...
    generate swat data for POST /hello ...
    generate swat route for /hello/world ...
    generate swat data for GET /hello/world ...


=head2 specify swat L<check lists|https://github.com/melezhik/swat#swat-check-lists>

This phase might be skipped as preliminary `200 OK` checks are already added on bootstrap phase. But you may define more. 

For complete documentation on *how to write swat tests*  please visit  https://github.com/melezhik/swat

    $ echo ROOT >> swat/get.txt
    $ echo HELLO >> swat/hello/post.txt
    $ echo HELLO WORLD >> swat/hello/world/get.txt


=head2 start mojo application

    $ morbo ./myapp.pl
    Server available at http://127.0.0.1:3000


=head2 run swat tests


=head1 SEE ALSO

=over

=item *

L<swat|https://github.com/melezhik/swat>


=item *

L<Mojolicious|https://metacpan.org/pod/Mojolicious>


=back
